-- Topic Activity Log and Per-Topic Book Lists
-- This migration adds topic activity tracking and converts book lists to per-topic

-- Create topic_activity table for tracking which topics had summaries generated
CREATE TABLE IF NOT EXISTS topic_activity (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES auth.users NOT NULL,
  topic_id UUID NOT NULL,
  topic_name TEXT NOT NULL,
  generated_at DATE NOT NULL DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, topic_id, generated_at)
);

-- Enable Row-Level Security
ALTER TABLE topic_activity ENABLE ROW LEVEL SECURITY;

-- RLS Policies for topic_activity
DROP POLICY IF EXISTS "Users can view own topic activity" ON topic_activity;
CREATE POLICY "Users can view own topic activity" ON topic_activity
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own topic activity" ON topic_activity;
CREATE POLICY "Users can insert own topic activity" ON topic_activity
  FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete own topic activity" ON topic_activity;
CREATE POLICY "Users can delete own topic activity" ON topic_activity
  FOR DELETE USING (auth.uid() = user_id);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_topic_activity_user_id ON topic_activity(user_id);
CREATE INDEX IF NOT EXISTS idx_topic_activity_topic_id ON topic_activity(topic_id);
CREATE INDEX IF NOT EXISTS idx_topic_activity_generated_at ON topic_activity(generated_at);

-- Modify book_lists table to support per-topic lists
ALTER TABLE book_lists ADD COLUMN IF NOT EXISTS topic_id UUID;
ALTER TABLE book_lists ADD COLUMN IF NOT EXISTS topic_name TEXT;

-- Drop old unique constraint and add new one
ALTER TABLE book_lists DROP CONSTRAINT IF EXISTS book_lists_user_id_quarter_key;
ALTER TABLE book_lists ADD CONSTRAINT book_lists_user_quarter_topic 
  UNIQUE(user_id, quarter, topic_id);

-- Create index for topic_id
CREATE INDEX IF NOT EXISTS idx_book_lists_topic_id ON book_lists(topic_id);

-- Note: Existing book_lists rows will have NULL topic_id/topic_name
-- These should be manually migrated or regenerated by users
